spring:
  application:
    name: hi-config
  cloud:
    config:
      server:
         git:
           uri: https://gitee.com/w77996/respo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
server:
  port: 9991