spring:
  application:
    name: hi-config
  cloud:
    config:
      server:
         git:
           uri: https://gitee.com/w77996/respo
  rabbitmq:
    host: 119.23.167.190
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9991
management:
  endpoint:
    web:
      expose: "*"