spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8880
zuul:
  routes:
  # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /myProduct/**
      serviceId: hi-product
      sensitiveHeaders:
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
